services:
  music-dl:
    image: cr.frogs.rocks/music_dl:latest
    container_name: music-dl
    restart: always
    pull_policy: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.musicdl.rule: "Host(`mdl.frogs.rocks`)"
      traefik.http.services.musicdl.loadbalancer.server.port: "8000"
      traefik.http.routers.musicdl.tls.certresolver: frogs_rocks
    volumes:
      - storage:/app/storage
    configs:
      - source: config
        target: /config.json
    environment:
      - PORT=8000
      - HOST=0.0.0.0

volumes:
  storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/mnt/pv/syncthing-data/Music

configs:
  config:
    content: |
      {
        "OUTPUT_DIR": "/app/storage"
      }