// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_kill from "./routes/api/kill.ts";
import * as $api_start from "./routes/api/start.ts";
import * as $api_ws from "./routes/api/ws.ts";
import * as $index from "./routes/index.tsx";
import * as $Home from "./islands/Home.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/kill.ts": $api_kill,
    "./routes/api/start.ts": $api_start,
    "./routes/api/ws.ts": $api_ws,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Home.tsx": $Home,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
